// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeXTJOjMFjUISsaz2ZEgWQdGa9c7_FXVQ',
    appId: '1:148505416044:web:c5cfbae5b15d736d1ae349',
    messagingSenderId: '148505416044',
    projectId: 'opvoedmaatje-f5ece',
    authDomain: 'opvoedmaatje-f5ece.firebaseapp.com',
    storageBucket: 'opvoedmaatje-f5ece.firebasestorage.app',
    measurementId: 'G-Z7PJQRR1QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Auw0kw3qU368dxlxuYDrguemno33oYk',
    appId: '1:148505416044:android:f76ccf016e37442a1ae349',
    messagingSenderId: '148505416044',
    projectId: 'opvoedmaatje-f5ece',
    storageBucket: 'opvoedmaatje-f5ece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_7_4wEZX0f08_tLW-7jwZWwQuhk5tIE4',
    appId: '1:148505416044:ios:18f139a8ad8d78411ae349',
    messagingSenderId: '148505416044',
    projectId: 'opvoedmaatje-f5ece',
    storageBucket: 'opvoedmaatje-f5ece.firebasestorage.app',
    iosBundleId: 'com.example.opvoedmaatje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_7_4wEZX0f08_tLW-7jwZWwQuhk5tIE4',
    appId: '1:148505416044:ios:18f139a8ad8d78411ae349',
    messagingSenderId: '148505416044',
    projectId: 'opvoedmaatje-f5ece',
    storageBucket: 'opvoedmaatje-f5ece.firebasestorage.app',
    iosBundleId: 'com.example.opvoedmaatje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeXTJOjMFjUISsaz2ZEgWQdGa9c7_FXVQ',
    appId: '1:148505416044:web:647e3270f7b660f91ae349',
    messagingSenderId: '148505416044',
    projectId: 'opvoedmaatje-f5ece',
    authDomain: 'opvoedmaatje-f5ece.firebaseapp.com',
    storageBucket: 'opvoedmaatje-f5ece.firebasestorage.app',
    measurementId: 'G-BM5YGQG6S6',
  );
}
